name: Validate (SELF)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    uses: sp0rk/chaffinch-gha/.github/workflows/lint.yml@main
    secrets:
      REVIEWDOG_TOKEN: ${{secrets.REVIEWDOG_TOKEN}}
    with:
      failOnError: true
      reporter: "github-pr-review"

  approve:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}